### 全件取得
GET http://localhost:3000/person/findAll
### 1件取得
GET http://localhost:3000/person/findById/4
### 1件更新
PATCH http://localhost:3000/person/update
content-type: application/json

{
  "id": 3,
  "name": "勇者ロト",
  "age": 15
}
### 1件作成
POST http://localhost:3000/person/create
content-type: application/json

{
  "id": 4,
  "name": "風来のシレン",
  "age": 12
}
### 1件削除
DELETE http://localhost:3000/person/delete/4

