### 全件取得
GET http://localhost:3000/persons
### 1件取得
GET http://localhost:3000/persons/4
### 1件更新
PATCH http://localhost:3000/persons/6
content-type: application/json

{
  "name": "チョコラブ",
  "age": 14
}
### 1件作成
POST http://localhost:3000/persons
content-type: application/json

{
  "name": "風来のシレン",
  "age": 12
}
### 1件削除
DELETE http://localhost:3000/persons/6

